package com.zte.model;

import java.io.Serializable;
import java.util.Date;

import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiModel;
        
@ApiModel("操作历史表")
public class TOperHis implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_oper_his.oper_his_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
    @ApiModelProperty(value ="操作历史ID")
	private Long operHisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_oper_his.oper_user_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
    @ApiModelProperty(value ="操作用户ID")
	private Long operUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_oper_his.function_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
    @ApiModelProperty(value ="功能ID")
	private Long functionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_oper_his.oper_time
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
    @ApiModelProperty(value ="操作类型")
	private Date operTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_oper_his.oper_content
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
    @ApiModelProperty(value ="操作时间")
	private String operContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_oper_his.remark
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
    @ApiModelProperty(value ="操作内容")
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_oper_his
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_oper_his.oper_his_id
	 * @return  the value of t_oper_his.oper_his_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public Long getOperHisId() {
		return operHisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_oper_his.oper_his_id
	 * @param operHisId  the value for t_oper_his.oper_his_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public void setOperHisId(Long operHisId) {
		this.operHisId = operHisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_oper_his.oper_user_id
	 * @return  the value of t_oper_his.oper_user_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public Long getOperUserId() {
		return operUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_oper_his.oper_user_id
	 * @param operUserId  the value for t_oper_his.oper_user_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public void setOperUserId(Long operUserId) {
		this.operUserId = operUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_oper_his.function_id
	 * @return  the value of t_oper_his.function_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public Long getFunctionId() {
		return functionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_oper_his.function_id
	 * @param functionId  the value for t_oper_his.function_id
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public void setFunctionId(Long functionId) {
		this.functionId = functionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_oper_his.oper_time
	 * @return  the value of t_oper_his.oper_time
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public Date getOperTime() {
		return operTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_oper_his.oper_time
	 * @param operTime  the value for t_oper_his.oper_time
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_oper_his.oper_content
	 * @return  the value of t_oper_his.oper_content
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public String getOperContent() {
		return operContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_oper_his.oper_content
	 * @param operContent  the value for t_oper_his.oper_content
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public void setOperContent(String operContent) {
		this.operContent = operContent == null ? null : operContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_oper_his.remark
	 * @return  the value of t_oper_his.remark
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_oper_his.remark
	 * @param remark  the value for t_oper_his.remark
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_oper_his
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TOperHis other = (TOperHis) that;
		return (this.getOperHisId() == null ? other.getOperHisId() == null
				: this.getOperHisId().equals(other.getOperHisId()))
				&& (this.getOperUserId() == null ? other.getOperUserId() == null
						: this.getOperUserId().equals(other.getOperUserId()))
				&& (this.getFunctionId() == null ? other.getFunctionId() == null
						: this.getFunctionId().equals(other.getFunctionId()))
				&& (this.getOperTime() == null ? other.getOperTime() == null
						: this.getOperTime().equals(other.getOperTime()))
				&& (this.getOperContent() == null ? other.getOperContent() == null
						: this.getOperContent().equals(other.getOperContent()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_oper_his
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getOperHisId() == null) ? 0 : getOperHisId().hashCode());
		result = prime * result + ((getOperUserId() == null) ? 0 : getOperUserId().hashCode());
		result = prime * result + ((getFunctionId() == null) ? 0 : getFunctionId().hashCode());
		result = prime * result + ((getOperTime() == null) ? 0 : getOperTime().hashCode());
		result = prime * result + ((getOperContent() == null) ? 0 : getOperContent().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_oper_his
	 * @mbg.generated  Mon Sep 23 16:37:18 CST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", operHisId=").append(operHisId);
		sb.append(", operUserId=").append(operUserId);
		sb.append(", functionId=").append(functionId);
		sb.append(", operTime=").append(operTime);
		sb.append(", operContent=").append(operContent);
		sb.append(", remark=").append(remark);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}
