package com.zte.model;

import java.util.ArrayList;
import java.util.List;

public class TSysParameterExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public TSysParameterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andParameterIdIsNull() {
			addCriterion("parameter_id is null");
			return (Criteria) this;
		}

		public Criteria andParameterIdIsNotNull() {
			addCriterion("parameter_id is not null");
			return (Criteria) this;
		}

		public Criteria andParameterIdEqualTo(Long value) {
			addCriterion("parameter_id =", value, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdNotEqualTo(Long value) {
			addCriterion("parameter_id <>", value, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdGreaterThan(Long value) {
			addCriterion("parameter_id >", value, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdGreaterThanOrEqualTo(Long value) {
			addCriterion("parameter_id >=", value, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdLessThan(Long value) {
			addCriterion("parameter_id <", value, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdLessThanOrEqualTo(Long value) {
			addCriterion("parameter_id <=", value, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdIn(List<Long> values) {
			addCriterion("parameter_id in", values, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdNotIn(List<Long> values) {
			addCriterion("parameter_id not in", values, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdBetween(Long value1, Long value2) {
			addCriterion("parameter_id between", value1, value2, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterIdNotBetween(Long value1, Long value2) {
			addCriterion("parameter_id not between", value1, value2, "parameterId");
			return (Criteria) this;
		}

		public Criteria andParameterNameIsNull() {
			addCriterion("parameter_name is null");
			return (Criteria) this;
		}

		public Criteria andParameterNameIsNotNull() {
			addCriterion("parameter_name is not null");
			return (Criteria) this;
		}

		public Criteria andParameterNameEqualTo(String value) {
			addCriterion("parameter_name =", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameNotEqualTo(String value) {
			addCriterion("parameter_name <>", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameGreaterThan(String value) {
			addCriterion("parameter_name >", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameGreaterThanOrEqualTo(String value) {
			addCriterion("parameter_name >=", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameLessThan(String value) {
			addCriterion("parameter_name <", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameLessThanOrEqualTo(String value) {
			addCriterion("parameter_name <=", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameLike(String value) {
			addCriterion("parameter_name like", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameNotLike(String value) {
			addCriterion("parameter_name not like", value, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameIn(List<String> values) {
			addCriterion("parameter_name in", values, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameNotIn(List<String> values) {
			addCriterion("parameter_name not in", values, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameBetween(String value1, String value2) {
			addCriterion("parameter_name between", value1, value2, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterNameNotBetween(String value1, String value2) {
			addCriterion("parameter_name not between", value1, value2, "parameterName");
			return (Criteria) this;
		}

		public Criteria andParameterValueIsNull() {
			addCriterion("parameter_value is null");
			return (Criteria) this;
		}

		public Criteria andParameterValueIsNotNull() {
			addCriterion("parameter_value is not null");
			return (Criteria) this;
		}

		public Criteria andParameterValueEqualTo(String value) {
			addCriterion("parameter_value =", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueNotEqualTo(String value) {
			addCriterion("parameter_value <>", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueGreaterThan(String value) {
			addCriterion("parameter_value >", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueGreaterThanOrEqualTo(String value) {
			addCriterion("parameter_value >=", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueLessThan(String value) {
			addCriterion("parameter_value <", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueLessThanOrEqualTo(String value) {
			addCriterion("parameter_value <=", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueLike(String value) {
			addCriterion("parameter_value like", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueNotLike(String value) {
			addCriterion("parameter_value not like", value, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueIn(List<String> values) {
			addCriterion("parameter_value in", values, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueNotIn(List<String> values) {
			addCriterion("parameter_value not in", values, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueBetween(String value1, String value2) {
			addCriterion("parameter_value between", value1, value2, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andParameterValueNotBetween(String value1, String value2) {
			addCriterion("parameter_value not between", value1, value2, "parameterValue");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_sys_parameter
	 * @mbg.generated  Mon Sep 23 17:26:31 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_parameter
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 23 16:37:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}